### ISSUE TITLE
Bug: Line wrapping not working on big screens

### ISSUE THREAD

**Issue by MustachedMario** [MaxLap/standard-notes-indent-editor#16]
Thank you for this wonderful sn editor!

As I understand the auto line wrapping function correctly, then all chars that passes the ~50 chars mark, should wrap into a paragraph.

- When I typing a long line on my ipad, it wraps around the 50th char.
- When I typing a long line on my surface 6, it wraps around the 50th char.
- But, when i typing a long line on my Desktop PC with a 32" monitor, the line wrap accours, when a natural wrap happens, while reaching the end of the line (around 200+ chars)

So i think this is a bug.

**Comment by MaxLap** [comment]
Hello, glad you like the editor!

Line wrapping always happens when there would be a natural wrapping. However when it does, the width of the paragraphs is limited. That's the way i intended it, as i use the editor mostly for list of things. I prefer a list of long lines with occasional paragraphs instead of having lots of paragraphs.

So I can't call it a bug, but it is not optimal if you often write lots of paragraph on wide screens. You end up with occasional long lines in your series of paragraphs.

Ideally, I would have a configuration per note to choose between some different wrapping behaviors. But I don't know how to do this in SN, and haven't found the time to figure it out and implement it.

**Comment by MustachedMario** [comment]
> Line wrapping always happens when there would be a natural wrapping. However when it does, the width of the paragraphs is limited. That's the way i intended it

Thats the way i expected it.
But if i have 3 diverent devices, and all 3 devices have a screensize to fit more than 100+ chars, why 2 of them wrap at 50 chars correctly, and one of them ot 200+ chars?
That was not my expectation.

**Comment by MaxLap** [comment]
On my laptop, the wrapping happens around 100 characters.
On my mobile phone, it is not wide enough, so wrapping is just the normal one and takes the whole width of the screen.
I don't have an iPad or a Surface, so I can't compare.

All i do is set a max-width of 50em on the line when it is naturally wrapping. Then, it will depend on font, font-size, browser, possibly on screen DPI, probably other things i'm not aware of.

Without being able to reproduce the problem, I can't help you.

**Comment by MustachedMario** [comment]
Ok, I get it. So forcing a wrap with e.g. shift+enter shortcut could be a solution?

As a workaround, I playing with the resize margin function that SN provides.
I set it to ~85 chars, so the wrap accours pretty on the same width on all devices.

And again, thanks for this editor!

**Comment by MaxLap** [comment]
Yeah, i guess if it doesn't happen too often, manually changing the line may be good enough of a work around.

And glad the margin resizer can make it more manageable. Good luck!

**Comment by MustachedMario** [comment]
Thanks for providing an option for this in the latest release!
