### ISSUE TITLE
Unable to add new lines to note via Android app

### ISSUE THREAD

**Issue by padraigkitterick** [MaxLap/standard-notes-indent-editor#23]
Using the indent editor on the official Standard Notes android app, I have run into an issue when using it to edit notes. If I place the cursor at the end of a line, whether it contains content or not, I would expect that pressing enter/return would insert a new line below. However, what happens is that when pressing enter/return the cursor moves to the next line but then returns to the end of the previous line, and I am unable to insert a new line. This does not appear to happen if you press enter/return when there is no content within the note.

All configuration settings for indent left to defaults.

Android app version: 3.6.23 (3000300)
Standard notes API version: 1.24.0 (self-hosted)

**Comment by MaxLap** [comment]
Hello, I'm sorry but I cannot reproduce the problem. I have no idea of anything within the editor that could produce that result. 

You say the cursor moves down, but then goes back. How long would you say is the delay between those movements?

Can you type words?

Have you tried in a new note and in an existing note?

Are you sure you are using indent editor? It's easy to not realize you are using the wrong editor on mobile, since the default is different from other platforms.

If you go to the demo here: https://maxlap.dev/standard-notes-indent-editor/demo.html, does the problem also happen?

**Comment by padraigkitterick** [comment]
Hi, here is a screen recording of accessing the demo webpage displaying the behaviour:

https://drive.google.com/file/d/1Mf6FqgMfrdaMkrqP2-GrvPaNARAvkjCW/view?usp=drivesdk

**Comment by MaxLap** [comment]
Wow, couldn't have had a better example. Thank you!

I have good and bad news...

Good: I managed to reproduce the problem.
Bad: I also produced many other weird bugs.

Good: A workaround the problem is to change the keyboard app you are using. From the look of it, I believe you are using Gboard. I reproduced the problem and others using GBoard. I personally use SwiftKey and do not experience any issue what so ever.

Bad: The problem is in the tool I use to make the editor, called CodeMirror. You can go on their demo and see the same problems: https://codemirror.net/demo/theme.html. 

Sorry, but I don't see how I can actually fix the problem or help with it other than recommend switching keyboard.

**Comment by padraigkitterick** [comment]
Many thanks for replicating and identifying the source of the bugs. It appears that there are a large number of Android bugs in CodeMirror 5.x and the developers suggest they may get squashed in the move to version 6.0. For now I'll try SwiftKey - thanks for the suggestion.
