### ISSUE TITLE
Editor displays Textinput Box instead of Note content

### ISSUE THREAD

**Issue by jrabensc** [MaxLap/standard-notes-indent-editor#9]
Hi, just encountered this error:
![image](https://user-images.githubusercontent.com/6616405/73934496-dc0cfe00-48de-11ea-8802-33b812db1345.png)

The note contains just a few random words.

SN Version 3.0.25
Editor Version 1.4.2

**Comment by MaxLap** [comment]
This is very odd... Only things I can think of:
* Try restarting the app
* Check if other editors (plain text doesn't count) work or not. (If not, the problem wouldn't be related to Indent Editor)
* Last resort, try uninstalling the Extension and adding it again. Here is the URL for the import: https://listed.to/p/eUPdNELfEu

If this is still not working, please post a screenshot of the top of the console so that the first errors can be seen, hopefully there would be something more useful.

**Comment by jrabensc** [comment]
Just started to work again after I checked a few hours later.

>     * Try restarting the app
Did not help at this point.
>     * Check if other editors (plain text doesn't count) work or not. (If not, the problem wouldn't be related to Indent Editor)
Other Editors were working.

I will watch out for this error in the next time and capture the error log if possible.

Thanks again for this awesome editor, it's by far my favorite.

**Comment by MaxLap** [comment]
Glad it solved itself and that you like the editor!
